
### LISTAR CONECTORES KAFKA
curl http://localhost:8083/connectors
####

curl -X POST \
  http://localhost:8083/connectors \
  -H "Content-Type: application/json" \
  -d @timescale-sink.json
###

curl http://localhost:8083/connectors/timescale-sink/status

####

curl -X POST http://localhost:8083/connectors \
  -H "Content-Type: application/json" \
  -d '{
  "name": "timescale-sink",
  "config": {
    "connector.class":
      "io.confluent.connect.jdbc.JdbcSinkConnector",

    "tasks.max": "1",

    "topics": "pamplona_vehicle",

    "connection.url":
      "jdbc:postgresql://timescale:5432/pamplona",

    "connection.user": "admin",
    "connection.password": "admin",

    "auto.create": "true",
    "auto.evolve": "true",
    "insert.mode": "insert",
    "table.name.format": "pamplona_vehicle"
  }
}'



#********************* VERSIONES *****************************
#ORION VERSION
###
GET http://localhost:1026/version

###


###
#VERSION IOT AGENT 
curl -X GET "http://localhost:4041/iot/about"
###

### saber grupos de dispositivos registrados
curl -X GET 'http://localhost:4041/iot/services' \
  -H 'Fiware-Service: pamplona' \
  -H 'Fiware-ServicePath: /urbanmobility'

### registrar un grupo de dispositivos
curl -X POST "http://localhost:4041/iot/services" \
  -H "Content-Type: application/json" \
  -H "fiware-service: pamplona" \
  -H "fiware-servicepath: /urbanmobility" \
  -d '{
    "services": [{
      "apikey": "123456789abcd",
      "cbroker": "http://orion:1026",
      "entity_type": "vehicle",
      "resource": "/iot/json"
    }]
  }'

###SUBSCRIPCIONES EN ORION DE CYGNUS
###
curl -X GET http://localhost:1026/v2/subscriptions/ \
  -H "Fiware-Service: pamplona" \
  -H "Fiware-ServicePath: /urbanmobility"

###
### DELETE SUBSCRIPCIONES EN ORION DE CYGNUS

curl -X DELETE  http://localhost:1026/v2/subscriptions/6a31332728214c0f5a0b24c4 \
  -H "Fiware-Service: pamplona" \
  -H "Fiware-ServicePath: /urbanmobility"


### SUBSCRIPCIONES EN ORION DE KAFKA
curl -iX POST \
  'http://localhost:1026/v2/subscriptions/' \
  -H 'Content-Type: application/json' \
  -H 'fiware-service: pamplona' \
  -H 'fiware-servicepath: /urbanmobility' \
  -d '{
  "description": "Notify kafka of all context changes",
  "subject": {
    "entities": [
      {
        "idPattern": ".*"
      }
    ]
  },
  "notification": {
    "http": {
      "url": "http://fastapi:8000/notify"
    }
  },
  "throttling": 0
}'
###



curl -i -X POST http://localhost:8083/connectors \
  -H "Content-Type: application/json" \
  -d '{
    "name": "timescale-sink",
    "config": {
      "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
      "tasks.max": "1",
      "topics": "pamplona_vehicle",
      "connection.url": "jdbc:postgresql://timescale:5432/fiware",
      "connection.user": "admin",
      "connection.password": "admin",
      "auto.create": "true",
      "auto.evolve": "true",
      "insert.mode": "insert",
      "table.name.format": "pamplona_vehicle"
    }
}'

###

curl http://localhost:8083/connector-plugins