events {}

http {
    upstream iot_agent {
        server iot-agent:4041;
    }

    upstream auth_service {
        server auth-service:3000;
    }

    server {
        listen 80;

        location = /auth {
            internal;
            proxy_pass http://auth_service/auth;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header Authorization $http_authorization;
            proxy_set_header X-Original-URI $request_uri;
        }

        location /iot/ {
            auth_request /auth;

            proxy_pass http://iot_agent;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Authorization $http_authorization;
        }
    }
}